/*
 * SEVEN_SEGMENT_BCD_program.c
 *
 * Created: 31/12/2023
 *  Author: Mahmoud Barakat
 */ 
/* SERVICE */
/* UTILES_LIB */
#include "../../SERVICE/UTILES_LIB/STD_TYPES.h"
#include "../../SERVICE/UTILES_LIB/BIT_MATH.h"

/* MCAL */
/* DIO */
#include "../../MCAL/DIO/DIO_interface.h"

/* HAL */
/* 7-segment */
#include "SEVEN_SEGMENT_BCD_config.h"
#include "SEVEN_SEGMENT_BCD_interface.h"

//Enable bit
extern u8 SEVEN_SEGMENT_BCD_ENport[SEVEN_SEGMENT_BCD_NUM];
extern u8 SEVEN_SEGMENT_BCD_ENpin[SEVEN_SEGMENT_BCD_NUM];

//DP bit
extern u8 SEVEN_SEGMENT_BCD_DPport[SEVEN_SEGMENT_BCD_NUM];
extern u8 SEVEN_SEGMENT_BCD_DPpin[SEVEN_SEGMENT_BCD_NUM];

//data bits 7 ---> A,B,C,D,E,F,G
extern u8 SEVEN_SEGMENT_BCD_DataPort[SEVEN_SEGMENT_BCD_NUM*4];
extern u8 SEVEN_SEGMENT_BCD_DataPins [SEVEN_SEGMENT_BCD_NUM*4];


/*************** APIS ***************/
SEVEN_SEGMENT_BCDStatus_t SEVEN_SEGMENT_BCD_init(u8 SEVEN_SEGMENTId,u8 dipstatus)
{u8 SEVEN_SEGMENT_BCD_counter=0;
	if (SEVEN_SEGMENTId < SEVEN_SEGMENT_BCD_NUM)
	{
		//enable 7-segment
		DIO_setPinDirection(SEVEN_SEGMENT_BCD_ENport[SEVEN_SEGMENTId],SEVEN_SEGMENT_BCD_ENpin[SEVEN_SEGMENTId],DIO_PIN_OUTPUT);
		if (dipstatus== dipused)
		{
			//enable DIP LED
			DIO_setPinDirection(SEVEN_SEGMENT_BCD_DPport[SEVEN_SEGMENTId],SEVEN_SEGMENT_BCD_DPpin[SEVEN_SEGMENTId],DIO_PIN_OUTPUT);
		}else
		{
			//do nothing
		}
		//enable 7-segment data LEDs
		for (SEVEN_SEGMENT_BCD_counter=(SEVEN_SEGMENTId*4);SEVEN_SEGMENT_BCD_counter<((SEVEN_SEGMENTId+1)*4);SEVEN_SEGMENT_BCD_counter++)
		{
			DIO_setPinDirection(SEVEN_SEGMENT_BCD_DataPort[SEVEN_SEGMENT_BCD_counter],SEVEN_SEGMENT_BCD_DataPins[SEVEN_SEGMENT_BCD_counter],DIO_PIN_OUTPUT);
		}
	}else
	{
		return SEVEN_SEGMENT_BCDIdError;
	}
	return SEVEN_SEGMENT_BCDNoError;
}
SEVEN_SEGMENT_BCDStatus_t SEVEN_SEGMENT_BCD_write(u8 SEVEN_SEGMENTId,u8 data)
{u8 SEVEN_SEGMENT_BCD_counter;
	if (SEVEN_SEGMENTId < SEVEN_SEGMENT_BCD_NUM)
	{
		#if   SEVEN_SEGMENT_BCD_TYPE == CATHODE_SEVEN_SEGMENT
		//enable 7-segment
		DIO_setPinValue(SEVEN_SEGMENT_BCD_ENport[SEVEN_SEGMENTId],SEVEN_SEGMENT_BCD_ENpin[SEVEN_SEGMENTId],DIO_PIN_LOW);
		
		for (SEVEN_SEGMENT_BCD_counter=(SEVEN_SEGMENTId*4);SEVEN_SEGMENT_BCD_counter<((SEVEN_SEGMENTId+1)*4);SEVEN_SEGMENT_BCD_counter++)
		{
			DIO_setPinValue(SEVEN_SEGMENT_BCD_DataPort[SEVEN_SEGMENT_BCD_counter],SEVEN_SEGMENT_BCD_DataPins[SEVEN_SEGMENT_BCD_counter],GET_BIT(data,SEVEN_SEGMENT_BCD_counter));
		}
		
		#elif SEVEN_SEGMENT_BCD_TYPE == ANODE_SEVEN_SEGMENT
		//enable 7-segment
		DIO_setPinValue(SEVEN_SEGMENT_BCD_ENport[SEVEN_SEGMENTId],SEVEN_SEGMENT_BCD_ENpin[SEVEN_SEGMENTId],DIO_PIN_HIGH);
		for (SEVEN_SEGMENT_BCD_counter=(SEVEN_SEGMENTId*4);SEVEN_SEGMENT_BCD_counter<((SEVEN_SEGMENTId+1)*4);SEVEN_SEGMENT_BCD_counter++)
		{
			DIO_setPinValue(SEVEN_SEGMENT_BCD_DataPort[SEVEN_SEGMENT_BCD_counter],SEVEN_SEGMENT_BCD_DataPins[SEVEN_SEGMENT_BCD_counter],GET_BIT(data,SEVEN_SEGMENT_BCD_counter));
		}
		#endif
	}else
	{
		return SEVEN_SEGMENT_BCDIdError;
	}
	return SEVEN_SEGMENT_BCDNoError;
}
SEVEN_SEGMENT_BCDStatus_t SEVEN_SEGMENT_BCD_off(u8 SEVEN_SEGMENTId)
{
	if (SEVEN_SEGMENTId < SEVEN_SEGMENT_BCD_NUM)
	{
		#if   SEVEN_SEGMENT_BCD_TYPE == CATHODE_SEVEN_SEGMENT
		//disable 7-segment
		DIO_setPinValue(SEVEN_SEGMENT_BCD_ENport[SEVEN_SEGMENTId],SEVEN_SEGMENT_BCD_ENpin[SEVEN_SEGMENTId],DIO_PIN_HIGH);
		#elif SEVEN_SEGMENT_BCD_TYPE == ANODE_SEVEN_SEGMENT
		//disable 7-segment
		DIO_setPinValue(SEVEN_SEGMENT_BCD_ENport[SEVEN_SEGMENTId],SEVEN_SEGMENT_BCD_ENpin[SEVEN_SEGMENTId],DIO_PIN_LOW);
		#endif
	}else
	{
		return SEVEN_SEGMENT_BCDIdError;
	}
	return SEVEN_SEGMENT_BCDNoError;
}
SEVEN_SEGMENT_BCDStatus_t SEVEN_SEGMENT_BCD_DPon(u8 SEVEN_SEGMENTId)
{
	if (SEVEN_SEGMENTId < SEVEN_SEGMENT_BCD_NUM)
	{
		#if   SEVEN_SEGMENT_BCD_TYPE == CATHODE_SEVEN_SEGMENT
		DIO_setPinValue(SEVEN_SEGMENT_BCD_DPport[SEVEN_SEGMENTId],SEVEN_SEGMENT_BCD_DPpin[SEVEN_SEGMENTId],DIO_PIN_HIGH);
		#elif SEVEN_SEGMENT_BCD_TYPE == ANODE_SEVEN_SEGMENT
		DIO_setPinValue(SEVEN_SEGMENT_BCD_DPport[SEVEN_SEGMENTId],SEVEN_SEGMENT_BCD_DPpin[SEVEN_SEGMENTId],DIO_PIN_LOW);
		#endif
	}else
	{
		return SEVEN_SEGMENT_BCDIdError;
	}
	return SEVEN_SEGMENT_BCDNoError;
}
SEVEN_SEGMENT_BCDStatus_t SEVEN_SEGMENT_BCD_DPoff(u8 SEVEN_SEGMENTId)
{
	if (SEVEN_SEGMENTId < SEVEN_SEGMENT_BCD_NUM)
	{
		#if   SEVEN_SEGMENT_BCD_TYPE == CATHODE_SEVEN_SEGMENT
		DIO_setPinValue(SEVEN_SEGMENT_BCD_DPport[SEVEN_SEGMENTId],SEVEN_SEGMENT_BCD_DPpin[SEVEN_SEGMENTId],DIO_PIN_LOW);
		#elif SEVEN_SEGMENT_BCD_TYPE == ANODE_SEVEN_SEGMENT
		DIO_setPinValue(SEVEN_SEGMENT_BCD_DPport[SEVEN_SEGMENTId],SEVEN_SEGMENT_BCD_DPpin[SEVEN_SEGMENTId],DIO_PIN_HIGH);
		#endif
	}else
	{
		return SEVEN_SEGMENT_BCDIdError;
	}
	return SEVEN_SEGMENT_BCDNoError;
}