/*
 * SEVEN_SEGMENT_BCD_BCD_config.c
 *
 * Created: 31/12/2023
 *  Author: Mahmoud Barakat
 */ 
/* SERVICE */
/* UTILES_LIB */
#include "../../SERVICE/UTILES_LIB/STD_TYPES.h"
#include "../../SERVICE/UTILES_LIB/BIT_MATH.h"

/* MCAL */
/* DIO */
#include "../../MCAL/DIO/DIO_interface.h"

/* HAL */
#include "SEVEN_SEGMENT_BCD_config.h"

//Enable bit
u8 SEVEN_SEGMENT_BCD_ENport[SEVEN_SEGMENT_BCD_NUM]={DIO_PORTB,DIO_PORTB};
u8 SEVEN_SEGMENT_BCD_ENpin[SEVEN_SEGMENT_BCD_NUM]={DIO_PIN1,DIO_PIN2};

//DP bit
u8 SEVEN_SEGMENT_BCD_DPport[SEVEN_SEGMENT_BCD_NUM]={DIO_PORTB};
u8 SEVEN_SEGMENT_BCD_DPpin[SEVEN_SEGMENT_BCD_NUM]={DIO_PIN3};
//data bits 7 ---> A,B,C,D,E,F,G
u8 SEVEN_SEGMENT_BCD_DataPort[SEVEN_SEGMENT_BCD_NUM*4]=
{
	DIO_PORTA,DIO_PORTA,DIO_PORTA,DIO_PORTA
};

u8 SEVEN_SEGMENT_BCD_DataPins [SEVEN_SEGMENT_BCD_NUM*4]=
{
	DIO_PIN4,DIO_PIN5,DIO_PIN6,DIO_PIN7,
	DIO_PIN4,DIO_PIN5,DIO_PIN6,DIO_PIN7
};